source "http://rubygems.org"

# App Stack
<% if @heroku -%>
gem "foreman"
gem "heroku"
<% end -%>
gem "sinatra"
gem "unicorn"

<% unless @no_database -%>
# Database Stack
<% unless @database == 'mongo' -%>
gem "sequel"
<% end -%>
<% if @database == "sqlite" -%>
<% if @heroku -%>
group :development, :test do
  gem "sqlite3"
end
<% else -%>
gem "sqlite3"
<% end -%>
<% elsif @database == "postgres" -%>
gem "pg"
<% elsif @database == "mysql" -%>
<% if @heroku -%>
group :development, :test do
  gem "mysql2"
end
<% else -%>
gem "mysql2"
<% end -%>
<% elsif @database == "mongo" -%>
gem "bson_ext"
gem "mongo_mapper"
<% end -%>
<% if @heroku && @database != "postgres" && @database != "mongo" -%>
group :production do
  gem "pg"
end
<% end -%>
<% if @redis -%>
# Redis
gem "redis"
<% end -%>
<% end -%>

